version: "3.8"

services:     
  grpc-service:
    image: grpc-service
    container_name: grpc-service
    build:
      context: .
      dockerfile: ./Service/Dockerfile
    ports:
      - 8080:80

  grpc-client:
    image: grpc-client
    container_name: grpc-client
    build:
      context: .
      dockerfile: ./Client/Dockerfile
    depends_on:
      - grpc-service
